### ISSUE TITLE
Save button is greyed out

### ISSUE THREAD

**Issue by Ads20000** [BryanLunduke/Linux-Tycoon#6]
I've had a distro running for 1600 days and my distro is at # 5 but the Save button is still greyed out...

<details>
<summary>Linux Tycoon 0.9.2 (2)</summary>

```
$ snap info linuxtycoon
tracking:  stable
refreshed: 2018-04-27T18:54:10+01:00
installed:   0.9.2 (2) 10MB -
$ snap version
snap    2.32.5+18.04
snapd   2.32.5+18.04
series  16
ubuntu  18.04
kernel  4.15.0-20-generic
$ snap info core
tracking:  beta
refreshed: 2018-04-16T11:33:06+01:00
installed:   16-2.32.5                (4486) 90MB core
```

</details>

**Comment by popey** [comment]
This bug is filed in the wrong place. This repo is for the linux version of LT, you want https://github.com/BryanLunduke/Linux-Tycoon-DOS

**Comment by Ads20000** [comment]
[Filed](https://github.com/BryanLunduke/Linux-Tycoon-DOS/issues/3)
